### ISSUE TITLE
Filter error

### ISSUE THREAD

**Issue by olivierdalang** [olivierdalang/liveStats#11]
Hi,
 I tried to use the QGIS plug-in "LiveStats" adding a filter, but the plug-in return an error. 

I try to explain you what I performed:

I have a table field whit a numeric code that identify administrative entities, this field is called cod_prov.

I want display the number of elements that have a certain code (i.e: cod_prov = 4). The function used is count.

To perform the query I put in the "filter (where)" the number 4, but the plug-in return this error:
Traceback (most recent call last):
  File "/home/enrico/.qgis2/python/plugins/LiveStats/LSbar.py", line 126, in dialogAccepted
    self.compute()
  File "/home/enrico/.qgis2/python/plugins/LiveStats/LSbar.py", line 229, in compute
    if not result.toBool():
AttributeError: 'int' object has no attribute 'toBool'

Versione Python:
2.7.6 (default, Mar 22 2014, 23:03:41)

Versione di QGIS:
2.7.0-Master Master, exported

I tried also add equal in to the query but the error in this case is 

PARSER ERROR: syntax error, unexpected EQ

How can i to perform the filter?

Thanks for the plug-in that is very useful and also for your eventual answer.

Regard

Enrico Fiore

**Comment by EnFiore** [comment]
Hi,
I am newbie both with github and pyqgis...but I tried to solve the issue. the solution is transform the variable _result_ (in line 226) on boolean whit this method 

**bool(result)**

and then remove the .toBool on line 229

so the plugin run correctly without error...

sorry for my poor explication but I don't know correct informatics terms to explain the solution.

Enrico Fiore
